services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_TEST_URI=mongodb://mongo:27017/expense-tracker-test
    command: npm run test
    networks:
      - backend

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
